#!/usr/bin/env bash
# Mello production install script for Linode (Debian/Ubuntu + Apache + Postgres).
# Idempotent. Non-destructive to existing services. Run as root.
set -euo pipefail

REPO_DIR="/opt/mello-repo"
SERVICE_USER="mello"
SERVICE_GROUP="mello"
SERVICE_HOME="/var/lib/mello"
ENV_DIR="/etc/mello"
ENV_FILE="${ENV_DIR}/mello.env"
NODE_PORT="2999"
DB_NAME="mello"
DB_USER="mello"
APACHE_SITE="mello"
APACHE_CONF="/etc/apache2/sites-available/${APACHE_SITE}.conf"

log() { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[err]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root."
[[ -d "$REPO_DIR" ]] || die "Expected repo at ${REPO_DIR}."

# ── 1. Prompt for domain + TLS contact email ──────────────────────────────────
read -r -p "Server name / domain for the Apache vhost (e.g. mello.example.com): " SERVER_NAME
[[ -n "${SERVER_NAME// }" ]] || die "Server name is required."
read -r -p "Email for Let's Encrypt registration / renewal notices: " LE_EMAIL
[[ -n "${LE_EMAIL// }" ]] || die "Email is required."

# ── 2. Node.js 20 (NodeSource) ────────────────────────────────────────────────
if ! command -v node >/dev/null 2>&1 || [[ "$(node -v 2>/dev/null | sed 's/v\([0-9]*\).*/\1/')" -lt 20 ]]; then
  log "Installing Node.js 20 via NodeSource"
  apt-get update
  apt-get install -y ca-certificates curl gnupg
  install -d -m 0755 /etc/apt/keyrings
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
    | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" \
    > /etc/apt/sources.list.d/nodesource.list
  apt-get update
  apt-get install -y nodejs
else
  log "Node.js $(node -v) already present — skipping"
fi

# ── 3. Service user/group (no shell) ──────────────────────────────────────────
if ! getent group "$SERVICE_GROUP" >/dev/null; then
  log "Creating group ${SERVICE_GROUP}"
  groupadd --system "$SERVICE_GROUP"
fi
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  log "Creating user ${SERVICE_USER} (no shell)"
  useradd --system --gid "$SERVICE_GROUP" \
          --home-dir "$SERVICE_HOME" --create-home \
          --shell /usr/sbin/nologin "$SERVICE_USER"
else
  install -d -o "$SERVICE_USER" -g "$SERVICE_GROUP" -m 0750 "$SERVICE_HOME"
fi

install -d -o "$SERVICE_USER" -g "$SERVICE_GROUP" -m 0700 "${SERVICE_HOME}/.npm"

# ── 4. Pull latest code (repo is root-owned) ──────────────────────────────────
if [[ -d "${REPO_DIR}/.git" ]]; then
  log "Pulling latest in ${REPO_DIR}"
  git -C "$REPO_DIR" pull --ff-only
fi

# ── 4b. Repo group ownership (do NOT change owner away from root) ─────────────
log "Setting group ownership on ${REPO_DIR} → ${SERVICE_GROUP}"
chgrp -R "$SERVICE_GROUP" "$REPO_DIR"
# group rwX so service user can run npm install (writes node_modules, dist)
chmod -R g+rwX "$REPO_DIR"
# setgid on dirs so future files inherit the mello group
find "$REPO_DIR" -type d -exec chmod g+s {} +

# Ensure runtime dirs exist & writable
install -d -g "$SERVICE_GROUP" -m 2775 "${REPO_DIR}/server/uploads"
install -d -g "$SERVICE_GROUP" -m 2775 "${REPO_DIR}/server/data"
install -d -g "$SERVICE_GROUP" -m 2775 "${REPO_DIR}/server/data/attachments"

# ── 5. Postgres role + database ───────────────────────────────────────────────
command -v psql >/dev/null || die "psql not found — Postgres required."

DB_PASSWORD=""
ROLE_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" || true)
if [[ "$ROLE_EXISTS" != "1" ]]; then
  DB_PASSWORD="$(head -c 32 /dev/urandom | base64 | tr -d '+/=' | head -c 32)"
  log "Creating Postgres role ${DB_USER}"
  sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
SQL
else
  log "Postgres role ${DB_USER} already exists"
  if [[ -f "$ENV_FILE" ]] && grep -q '^DATABASE_URL=' "$ENV_FILE"; then
    warn "Reusing DATABASE_URL from ${ENV_FILE}"
  else
    die "Role ${DB_USER} exists but no ${ENV_FILE}. Drop the role manually or restore the env file before re-running."
  fi
fi

DB_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" || true)
if [[ "$DB_EXISTS" != "1" ]]; then
  log "Creating Postgres database ${DB_NAME}"
  sudo -u postgres createdb -O "${DB_USER}" "${DB_NAME}"
else
  log "Postgres database ${DB_NAME} already exists"
fi

# ── 6. Env file ───────────────────────────────────────────────────────────────
install -d -g "$SERVICE_GROUP" -m 0750 "$ENV_DIR"
if [[ ! -f "$ENV_FILE" ]]; then
  log "Writing ${ENV_FILE}"
  SESSION_SECRET="$(head -c 48 /dev/urandom | base64 | tr -d '\n')"
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by install-prod.sh on $(date -Iseconds)
NODE_ENV=production
PORT=${NODE_PORT}
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}
REDIS_URL=redis://localhost:6379
SESSION_SECRET=${SESSION_SECRET}
BASE_URL=https://${SERVER_NAME}
TLS_EMAIL=${LE_EMAIL}
STORAGE_PATH=${REPO_DIR}/server/data/attachments
EOF
  chgrp "$SERVICE_GROUP" "$ENV_FILE"
  chmod 0640 "$ENV_FILE"
else
  log "${ENV_FILE} already exists — leaving in place"
fi

# ── 7. npm install + build (as service user) ──────────────────────────────────
run_as_mello() {
  sudo -u "$SERVICE_USER" \
    HOME="$SERVICE_HOME" \
    npm_config_cache="${SERVICE_HOME}/.npm" \
    PATH="/usr/bin:/usr/local/bin:$PATH" \
    bash -c "cd '${REPO_DIR}' && umask 002 && $*"
}

log "Installing npm workspaces"
run_as_mello "npm install --no-audit --no-fund"

log "Building shared + client + server (clean)"
# Wipe old dist/ output so removed source files don't linger and break ESM resolution.
rm -rf "${REPO_DIR}/packages/shared/dist" \
       "${REPO_DIR}/server/dist" \
       "${REPO_DIR}/client/dist"
run_as_mello "npm run build"

log "Running database migrations"
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a
run_as_mello "cd server && DATABASE_URL='${DATABASE_URL}' npx drizzle-kit migrate"

# ── 8. Apache vhost + TLS ─────────────────────────────────────────────────────
log "Enabling required Apache modules"
a2enmod proxy proxy_http proxy_wstunnel headers rewrite ssl http2 >/dev/null

# certbot for TLS issuance/renewal (webroot mode — does NOT touch our vhost file)
if ! command -v certbot >/dev/null 2>&1; then
  log "Installing certbot"
  apt-get install -y certbot
fi

ACME_WEBROOT="/var/www/mello-acme"
install -d -m 0755 "$ACME_WEBROOT"

CERT_DIR="/etc/letsencrypt/live/${SERVER_NAME}"

# Step 1: write a minimal HTTP-only vhost so certbot --webroot can answer the
# ACME http-01 challenge. We replace this with the real config after issuance.
if [[ ! -f "${CERT_DIR}/fullchain.pem" ]]; then
  log "Writing temporary HTTP vhost for ACME challenge"
  cat > "$APACHE_CONF" <<EOF
# Mello — temporary ACME bootstrap (managed by install-prod.sh)
<VirtualHost *:80>
    ServerName ${SERVER_NAME}
    DocumentRoot ${ACME_WEBROOT}
    <Directory ${ACME_WEBROOT}>
        Require all granted
    </Directory>
</VirtualHost>
EOF
  a2ensite "$APACHE_SITE" >/dev/null
  apache2ctl configtest
  systemctl reload apache2

  log "Requesting Let's Encrypt certificate for ${SERVER_NAME}"
  certbot certonly --webroot -w "$ACME_WEBROOT" \
    -d "$SERVER_NAME" \
    --non-interactive --agree-tos -m "$LE_EMAIL" \
    --keep-until-expiring
else
  log "Existing certificate found at ${CERT_DIR} — skipping issuance"
fi

[[ -f "${CERT_DIR}/fullchain.pem" ]] || die "Certificate not present at ${CERT_DIR}; cannot enable HTTPS."

log "Writing final HTTPS vhost ${APACHE_CONF}"
cat > "$APACHE_CONF" <<EOF
# Mello — managed by install-prod.sh

# HTTP: serve ACME challenges, redirect everything else to HTTPS.
<VirtualHost *:80>
    ServerName ${SERVER_NAME}
    DocumentRoot ${ACME_WEBROOT}

    Alias /.well-known/acme-challenge/ ${ACME_WEBROOT}/.well-known/acme-challenge/
    <Directory ${ACME_WEBROOT}/.well-known/acme-challenge/>
        Require all granted
    </Directory>

    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName ${SERVER_NAME}

    SSLEngine on
    SSLCertificateFile      ${CERT_DIR}/fullchain.pem
    SSLCertificateKeyFile   ${CERT_DIR}/privkey.pem

    Protocols h2 http/1.1

    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"

    DocumentRoot ${REPO_DIR}/client/dist

    <Directory ${REPO_DIR}/client/dist>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
        # SPA fallback
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_URI} !^/(api|uploads|socket\.io)/
        RewriteRule ^ index.html [L]
    </Directory>

    # WebSocket upgrade for Socket.IO
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule ^/socket\.io/(.*)\$ ws://127.0.0.1:${NODE_PORT}/socket.io/\$1 [P,L]

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    ProxyPass        /api/        http://127.0.0.1:${NODE_PORT}/api/
    ProxyPassReverse /api/        http://127.0.0.1:${NODE_PORT}/api/
    ProxyPass        /uploads/    http://127.0.0.1:${NODE_PORT}/uploads/
    ProxyPassReverse /uploads/    http://127.0.0.1:${NODE_PORT}/uploads/
    ProxyPass        /socket.io/  http://127.0.0.1:${NODE_PORT}/socket.io/
    ProxyPassReverse /socket.io/  http://127.0.0.1:${NODE_PORT}/socket.io/

    ErrorLog  \${APACHE_LOG_DIR}/mello_error.log
    CustomLog \${APACHE_LOG_DIR}/mello_access.log combined
</VirtualHost>
EOF

a2ensite "$APACHE_SITE" >/dev/null

# Make sure certbot reloads apache after future renewals (idempotent).
install -d -m 0755 /etc/letsencrypt/renewal-hooks/deploy
cat > /etc/letsencrypt/renewal-hooks/deploy/reload-apache.sh <<'EOF'
#!/bin/sh
systemctl reload apache2 || true
EOF
chmod 0755 /etc/letsencrypt/renewal-hooks/deploy/reload-apache.sh

log "Validating Apache config"
apache2ctl configtest

log "Reloading Apache (graceful, no restart)"
systemctl reload apache2

cat <<DONE

\033[1;32mMello install complete.\033[0m
  Repo:       ${REPO_DIR}
  Env:        ${ENV_FILE}
  Service:    user=${SERVICE_USER} (nologin), group=${SERVICE_GROUP}
  Node port:  ${NODE_PORT} (loopback)
  Vhost:      https://${SERVER_NAME}/  (HTTP redirects to HTTPS)
  TLS:        Let's Encrypt (auto-renew via certbot.timer + deploy hook)

Next step:
  • Start the app:   sudo ${REPO_DIR}/start-prod.sh
DONE
